### PR TITLE
Added PIP layer support for VX1000

### PR DESCRIPTION
**Pull request by cyberblaststudios**
This pull request includes changes to allow support for utilizing the PIP layer options on the Novastar VX1000 LED Video Wall Processor with Bitfocus Companion. This feature will allow companion users to configure every PIP layer parameter that the Novastar protocol makes available through a companion button.

If you have any questions about this pull request, please let me know.
image

### CODE REVIEW

**Comment by Lordgrifis** [comment]
thanks, that's what I need.
can you please help me ? how I can add this to companion?

**Comment by cyberblaststudios** [comment]
> thanks, that's what I need. can you please help me ? how I can add this to companion?

I would be best if we wait until this is merged into the master branch and pulled into Companion v2, then it should work seamlessly inside of Companion.

**Comment by Lordgrifis** [comment]
> > thanks, that's what I need. can you please help me ? how I can add this to companion?
> 
> I would be best if we wait until this is merged into the master branch and pulled into Companion v2, then it should work seamlessly inside of Companion.

thanks, I need just open and close layer 2 and layer 3
can you please hel me with hex string?
I can use generic tcp-udp to send the string but I'm not able to calculate the 4 string I need
thanks a lot

**Comment by cyberblaststudios** [comment]
closed PR, as we cannot merge any features with V2.0 modules, so I am working on moving this to a v3.0 module with the PIP and layering changes. I will have another PR when I finish.

**Pull request closed without merging**
